import React from 'react';

class AboutYerkaland extends React.Component {
    render() {
        return <div className="about_yerkaland">
        <div className="container">
            <div className="about-yerkaland-header">
                <h1>Lorem Yerkaland ipsum</h1>
            </div>
            <div className="about-yerkaland-text">
                <p><img src="https://lh3.googleusercontent.com/x4QvwTuhopQPrPh8ZJRcCWhvxMLUqrCmKot28Y1Ib_gSwomUSS61GbvOtoryLTKp1rAYRD-8vmjgDq446i5YWZERV5NrVULxdIm9O_ks6wtZyPySyB0ogR-QmmlTw2WlNyh8xQ-2q7c_BKCToEO1tVrow249A7988l8-ImToNb3wtqaR29y2cySwO-tsI9GJ99PpdOHcCsIAPit_FLti2jlIUvIJnK08fll6oOUOnY6sbt-xGnty0KACkkKvUHsNhczaZl73X1oPnrFDGKWCXQhXEJFbYiETiiE_MTMXnAgomGuWU9CC5zGMlCg1WJ8ffkAbSgxy8jz8L0alRhz2H4tvT0-rMyGO-Hv30lqdynjKYJ4WjwkTI4EuNsWJPhAM83gbSXM_XAGvUlWPHCKMM-OP4BqQQ50UJkkqptlCyFRbe2ltQUP1UQURWmO9ocu45PrinTYiDTtMcPgTV9Jvo4eudaIoODOu9JJA7r86XoEN_dr-9bdkSU4GByIC4S0x_1wyIiBwwu_H4f5zVrZggT5vyQ466_4NF3brsxv27NCftjTSu8x1m4Pm6uv88EAFwkxGQzDy4vViPz1iwzxo_QWaywvdtCNKdo5uQXU=w575-h507-no" className="about-yerkaland-photo-left"/>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc id auctor nibh, a fringilla eros. Sed eu nibh vitae libero auctor malesuada eget at nisl. Ut feugiat ante nec arcu sodales, ut tincidunt nibh tempor. Morbi mauris libero, pharetra sed nunc suscipit, dictum iaculis enim. Sed consequat tellus eget sem posuere, sit amet vestibulum mi condimentum. Nulla nisl lacus, ultricies ut tincidunt lobortis, facilisis et massa. Donec fermentum velit eleifend, rhoncus tellus eget, tempus odio. Curabitur sit amet eleifend felis. Vivamus a elit sed nibh sodales blandit id et lorem. Morbi at libero vel lacus luctus bibendum. Nullam varius elit tortor, et pulvinar nisi volutpat venenatis.</p>
                
                
                <p>Vivamus eget sollicitudin justo. Proin volutpat fermentum egestas.  Donec sit amet nisl in lectus elementum tincidunt. Suspendisse porttitor metus quis justo dapibus lacinia mattis quis massa. Donec a libero dapibus, vestibulum elit at, elementum libero. Vestibulum in gravida augue, eget fermentum justo. Etiam tincidunt nunc sed sollicitudin ultrices. Etiam vitae varius velit, nec ultricies augue. Integer iaculis elit tortor, sed eleifend felis porttitor sed. Maecenas tellus eros, interdum ut laoreet quis, dignissim et lacus.</p>
               
                <p>Cras efficitur nisi imperdiet viverra dapibus. <img src="https://lh3.googleusercontent.com/Gkb_Idu94tYBsoDpSaccFouPvQxNI3tIFoCbdTQxfTLK6-KGSiwwSItzBmKi14khZbs2_2kg2YGLqGbYWftRRQFXNMduV0HMtmRUYE4dUlmXDYM3tbmd0LvnP6d_1eGUVBgfjdOwMIDTYFmpsTanpbcEbEr4KPyh8yT4UWEcPEM-i4hfOMoxzJKPbb87r38uGwa_PY3ka2womYRGrhEBmq7QC1Vo2MgPmKLiXrpe1pN83ndWe8GCNQ1q7sM8APzKdJ8PoGvLsG9FDMca6f17WsQjrbgpITObujBhWlDLrc-nwcPRvtGg6bGBw_95am3PXwXdafJRFkUtxJutEafJ8Xdgs3J3w8dHwYkI7zNZoZuq6yVMdfH4XKGPsGa07cft3hKnq1SxT2n_hH5t8ZLT_IQ9-LlYVA31DIgevHmHeBXm_gOJT6xpuAKJyAmMw-sPiTlBBlinoyuZAmc2UKA5ETusY18p-LecLubH72AdY_kPcETreX96PfKfwColmKUuTMeGdp3NYKYl9Xn64AUlEXBwEWDJ_uPocVMlnEVWeqGHMq7y3NV3urWW3U0054kgrLE8fle6wDrlnCuy1zXcgjxq3xs8lJmSc01k8x8=w636-h507-no" className="about-yerkaland-photo-right"/> Maecenas pulvinar eu lorem eu consequat. Duis dignissim lacinia nunc, ut consequat orci accumsan et. Nunc faucibus mauris at lorem porta, ac condimentum justo sollicitudin. Fusce malesuada ligula molestie nulla viverra, eu pellentesque tellus feugiat. Etiam at dolor in quam convallis lacinia. Sed in mauris vitae lorem malesuada molestie varius viverra turpis. Donec eu molestie nisl, id faucibus sapien. Aenean finibus metus eu maximus sollicitudin. Pellentesque interdum lacus ut elit semper, et venenatis lacus vehicula. Fusce gravida gravida erat. Maecenas hendrerit placerat odio, ut feugiat metus. Nulla lobortis sagittis lobortis.</p>
                        
                <p>Ut mattis diam vel commodo ullamcorper. Phasellus elementum nisl tortor, ut mollis velit consequat ac. Cras faucibus venenatis molestie. Fusce vel rutrum nulla, nec bibendum felis. Donec sit amet nulla ut magna eleifend semper vitae vitae purus. Vestibulum libero ante, mollis eu sapien non, varius suscipit eros. Nullam egestas consequat lorem nec dapibus. Morbi mauris tellus, lobortis aliquet tristique in, gravida non purus. In mauris turpis, volutpat eu vehicula commodo, tincidunt quis libero. Vivamus tincidunt felis non nisi tristique, sed convallis dolor tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
                
                <img src="https://lh3.googleusercontent.com/2bFcIV_wV68R_vpzlBHyjHWHAsUMMsisI8XrLqY-YExC3k_7lnJa0LDkCgMEOpdsnvO9Kil0sSTIGwUXy9RC8VB1jBdW6Qq2YJdsFSOWW8YTSsenQ9lhS35stP9RSfrLFGtxvQCKSl4kfBD4xrU__ESw2sYSd9Ngv0lJHCeBkaz3T9X0KZrWeirxXWFfGMokCx7z11uaFDo9O5zK-_sSqwZmYXRwZ79DFYyntCwwcBO0JT2J3QrxinqTKAjmnv-Qz-lfT8cKGd_2xHuWolwOu7utB1-QXD5aqY0blP1kk6TXeEH4OvgU6eJdzmzOGll1iSiM3FFTEYBhlqIxwLlqmg-cnJOiN7G7-IlHcne2EAXAIio4sKBWG1Ig5wWkd20IQBsSdBd0O-XvB2IeXOE4PsFYsiEl34Y-Q77a6IBlrIVRbzFluBEOVBHOH4He3_BIvuGdiHCbXg2tKlTIJec9edGsVwc5QMLLpDuRPOdbCsKbGpIWmcoPJWYMFg4degU8MKjuO-tCoFTtN1JRs0fmAykEv_7xt6ngdRAhzKoP679UAgLEg5yuq2_4318B9bSiyIiSLJaoYq3KRpl8-wy1PUiNMLwMsLfZxQyzFtQ=w638-h507-no" className="about-yerkaland-photo-last"/>
                <p>Proin varius nibh quis ex rutrum, at lobortis quam lobortis. Donec sodales bibendum sollicitudin. Ut efficitur viverra nulla, non lobortis purus elementum nec. Curabitur mollis iaculis ultrices. Fusce tempor, arcu in finibus feugiat, libero eros pharetra nisi, vitae vestibulum lectus nunc at ante. Aliquam erat volutpat. Nullam malesuada elementum pulvinar. Phasellus aliquam, massa posuere venenatis faucibus, tortor lacus aliquam quam, sit amet ultrices mauris ante in magna.</p>
                
                <p>Suspendisse sit amet nisl at nisl varius fringilla. Cras ac libero mi. Mauris molestie est at orci porta, non ullamcorper ligula posuere. Suspendisse elit dui, bibendum quis mollis eget, egestas quis dui. In vehicula vestibulum risus, et aliquam erat lobortis sed. Pellentesque blandit id erat ullamcorper pharetra. Nunc volutpat odio dui, ut semper arcu suscipit in. Quisque ante ex, tincidunt vitae.</p>
            </div>
        </div>
    </div>
    }
}

export {AboutYerkaland}